/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agentcommgui;

import behaviours.SendMessage;
import jade.core.AID;
import jade.domain.FIPAException;
import jade.lang.acl.ACLMessage;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ethan_Hunt
 */
public class AgentForm2 extends javax.swing.JFrame {
    
    private AgentCommGUI myAgent;
    private String [] messagePerformatives;
    
    /**
     * Creates new form AgentForm2
     */
    public AgentForm2() {
        initComponents();
        setVisible(true);
        messagePerformatives = ACLMessage.getAllPerformativeNames();
        comboBoxMessagePerf.setModel(new javax.swing.DefaultComboBoxModel(messagePerformatives));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSentMessages = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaReceivedMessages = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        comboBoxMessagePerf = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldContent = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        comboBoxAgensList = new javax.swing.JComboBox();
        buttonRefreshAgents = new javax.swing.JButton();
        textFieldRemotePlatformName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textfieldRemoteAddress = new javax.swing.JTextField();
        buttonAddRemoteAgents = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaSentMessages.setColumns(20);
        textAreaSentMessages.setRows(5);
        jScrollPane1.setViewportView(textAreaSentMessages);

        jLabel1.setText("Sent Messages");

        jLabel2.setText("Received Messages");

        textAreaReceivedMessages.setColumns(20);
        textAreaReceivedMessages.setRows(5);
        jScrollPane2.setViewportView(textAreaReceivedMessages);

        jLabel5.setText("Message Performative");

        comboBoxMessagePerf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Request", "Inform" }));
        comboBoxMessagePerf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMessagePerfActionPerformed(evt);
            }
        });

        jLabel3.setText("Local Platform Receivers");

        jLabel4.setText("Content");

        buttonSend.setText("Send");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");

        comboBoxAgensList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonRefreshAgents.setText("refresh agents");
        buttonRefreshAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshAgentsActionPerformed(evt);
            }
        });

        textFieldRemotePlatformName.setText("dfplatformname");

        jLabel6.setText("Remote Platform");

        textfieldRemoteAddress.setText("address");

        buttonAddRemoteAgents.setText("add remote agents");
        buttonAddRemoteAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddRemoteAgentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxMessagePerf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(245, 245, 245))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldContent, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(buttonSend)
                                        .addGap(30, 30, 30)
                                        .addComponent(buttonCancel))
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textFieldRemotePlatformName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textfieldRemoteAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(comboBoxAgensList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(buttonRefreshAgents))
                                    .addComponent(buttonAddRemoteAgents))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(comboBoxMessagePerf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxAgensList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRefreshAgents))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldRemotePlatformName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldRemoteAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonAddRemoteAgents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSend)
                            .addComponent(buttonCancel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMessagePerfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMessagePerfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMessagePerfActionPerformed

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        String messageContent = textFieldContent.getText();
        int messagePerf = comboBoxMessagePerf.getSelectedIndex();        
        int receiverIndex = comboBoxAgensList.getSelectedIndex();
        AID receiverAID = myAgent.agentsList.get(receiverIndex);
        //String receiver = (String)comboBoxAgensList.getSelectedItem();
        
        ACLMessage msg = new ACLMessage(messagePerf);
       // msg.addReceiver(new AID(receiver, AID.ISLOCALNAME)); //here the name of the agent is already known
        msg.addReceiver(receiverAID);
        msg.setLanguage("English");
        msg.setContent(messageContent);

        SendMessage sm = new SendMessage(msg, myAgent);
        myAgent.addBehaviour(sm);

    }//GEN-LAST:event_buttonSendActionPerformed

    private void buttonRefreshAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshAgentsActionPerformed
        try {
            myAgent.RefetchAgentsList();
        } catch (FIPAException ex) {
            Logger.getLogger(AgentForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
        populateAgentsListOnGUI();
        
    }//GEN-LAST:event_buttonRefreshAgentsActionPerformed

    private void buttonAddRemoteAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddRemoteAgentsActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                String remotePlatformName =  textFieldRemotePlatformName.getText();
                String remotePlatformAddress = textfieldRemoteAddress.getText();
                AID remoteDF = new AID(remotePlatformName,AID.ISGUID);
                remoteDF.addAddresses(remotePlatformAddress);
                myAgent.remoteDF = remoteDF;
                try {
                    myAgent.RefetchAgentsList();
                    populateAgentsListOnGUI();
                } catch (FIPAException ex) {
                    Logger.getLogger(AgentForm2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
        
    }//GEN-LAST:event_buttonAddRemoteAgentsActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentForm2().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddRemoteAgents;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonRefreshAgents;
    private javax.swing.JButton buttonSend;
    private javax.swing.JComboBox comboBoxAgensList;
    private javax.swing.JComboBox comboBoxMessagePerf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaReceivedMessages;
    private javax.swing.JTextArea textAreaSentMessages;
    private javax.swing.JTextField textFieldContent;
    private javax.swing.JTextField textFieldRemotePlatformName;
    private javax.swing.JTextField textfieldRemoteAddress;
    // End of variables declaration//GEN-END:variables

    public void setAgent(AgentCommGUI a) {
        myAgent = a;
    }
    
    public void setContentText(String content){
        textAreaReceivedMessages.setText(content);
    }

    public void appendReceivedMessagesText(String theMessage){
        textAreaReceivedMessages.append(theMessage);
    }
    
    public void appendSentMessagesText(String theMessage){
        textAreaSentMessages.append(theMessage);
    }
    
    public void populateAgentsListOnGUI(){
        if (myAgent.agentsList!=null){
            String[]agentsArray = new String[myAgent.agentsList.size()];
            for (int i=0;i<agentsArray.length;i++){
                agentsArray[i]=myAgent.agentsList.get(i).getName();
            }
            comboBoxAgensList.setModel(new javax.swing.DefaultComboBoxModel(agentsArray));
        }
    }
    
}
